---
- name: Setup with root
  hosts: laptop
  roles:
    - role: yubikey
  tasks:
    - name: Basic packages
      ansible.builtin.package:
        name:
          - vim
          - tmux

- name: Setup with local user
  hosts: laptop_user
  roles:
    - dotfiles
