---
- name: Setup with root
  hosts: laptop
  roles:
    - role: yubikey
    - role: workstation_hardening
    - role: firefox
    - role: vscode
    - role: plymouth
    - role: base_packages
      vars:
        base_packages_extra:
          - ansible-lint
          - podman
          - podman-compose
          - bubblewrap
          - oras
          - neovim
          - neovim-qt
          # kvm
          - qemu-system
          - libvirt-daemon-system
          - virt-manager
          - guestfs-tools
          # webcam
          - uvcdynctrl
  tasks:
    - name: Set webcam powerline freq to 50hz
      ansible.builtin.copy:
        dest: "/etc/udev/rules.d/81-uvcvideo.rules"
        owner: root
        group: root
        mode: '0644'
        content: >
          # Set power line frequency to 50 Hz

          ACTION=="add", SUBSYSTEM=="video4linux", DRIVERS=="uvcvideo",
          RUN+="/usr/bin/uvcdynctrl -d$kernel '--set=Power Line Frequency' 1"

- name: Setup with local user
  hosts: laptop_user
  roles:
    - fonts
    - dotfiles
    - user_setup
    - role: onepassword
      vars:
        onepassword_install_cli: true
    - kde_settings
    - jetbrains_toolbox

  tasks:
    - name: Enable podman socket for user
      ansible.builtin.systemd_service:
        name: podman.socket
        scope: user
        enabled: true
        state: started

    # There are a bunch of ssh agents lined up start and be in the way
    # Disable & mask them all
    - name: Disable user ssh-agent service
      ansible.builtin.systemd_service:
        name: "{{ item }}"
        scope: user
        masked: true
        state: stopped
      loop:
        - ssh-agent.service
        - ssh-agent.socket
        - gcr-ssh-agent.service
        - gcr-ssh-agent.socket

    - name: Install python packages to create venv
      become: true
      ansible.builtin.package:
        name:
          - python3-venv
          - python3-pip

    - name: Install molecule in venv
      ansible.builtin.pip:
        name:
          - molecule
          - molecule-plugins
        virtualenv: ~/.venv/molecule
        virtualenv_command: 'python3 -m venv'

    - name: Add user to the libvirt group to enable VM management
      become: true
      ansible.builtin.user:
        name: "{{ ansible_user_id }}"
        append: true
        groups: libvirt

    - name: Create .ssh directory for user
      ansible.builtin.file:
        path: "~/.ssh"
        state: directory
        mode: '0700'

    - name: Create .ssh/config.d/ directory for user
      ansible.builtin.file:
        path: "~/.ssh/config.d"
        state: directory
        mode: '0700'

    - name: Configure ssh config
      ansible.builtin.copy:
        dest: "~/.ssh/config"
        content: |
          # Desktop Apps will not see the SSH_AUTH_SOCK from the dotfiles
          Host *
              IdentityAgent ~/.1password/agent.sock

          Include ~/.ssh/config.d/*
        mode: '0600'

    - name: Additional ssh config snippets
      ansible.builtin.copy:
        dest: "~/.ssh/config.d/additional-config.conf"
        content: |
          {{ ssh_additional_config | join('\n\n') }}
        mode: '0600'
