---
- name: Setup with root
  hosts: laptop
  roles:
    - role: yubikey
    - role: firefox
    - role: base_packages
      vars:
        base_packages_extra:
          - ansible-lint
          - podman
          - podman-compose
          # kvm
          - qemu-system
          - libvirt-daemon-system
          - virt-manager

- name: Setup with local user
  hosts: laptop_user
  roles:
    - fonts
    - dotfiles
    - user_setup
    - onepassword

  tasks:
    - name: Enable podman socket for user
      ansible.builtin.systemd_service:
        name: podman.socket
        scope: user
        enabled: true
        state: started

    - name: Install python packages to create venv
      become: true
      ansible.builtin.package:
        name:
          - python3-venv
          - python3-pip

    - name: Install molecule in venv
      ansible.builtin.pip:
        name:
          - molecule
          - molecule-plugins
        virtualenv: ~/.venv/molecule
        virtualenv_command: 'python3 -m venv'

    - name: Add user to the libvirt group to enable VM management
      become: true
      ansible.builtin.user:
        name: "{{ ansible_user_id }}"
        append: true
        groups: libvirt
