---
- name: Setup with root
  hosts: local
  roles:
    - role: base_packages
      vars:
        base_packages_extra:
          - ansible-lint
          - podman
          - podman-compose
          - bubblewrap
          - oras
          # kvm
          - qemu-system
          - guestfs-tools

- name: Setup with local user
  hosts: local_user
  roles:
    - dotfiles
    - user_setup
    - role: onepassword
      vars:
        onepassword_install_cli: true
    - role: ssh_user_config
  tasks:
    - name: "Create aliases for ssh"
      ansible.builtin.lineinfile:
        create: true
        dest: "~/.config/setup/env.local.sh"
        line: "{{ item }}"
      with_items:
        - "alias ssh=ssh.exe"
        - "alias ssh-add=ssh-add.exe"
        - "alias scp=scp.exe"

    - name: Add the current user to kvm group
      become: true
      ansible.builtin.user:
        name: "{{ ansible_user_id }}"
        append: true
        groups: kvm
