---
all:
  hosts:
    local:
      ansible_connection: local
      ansible_become: true
    local_user:
      ansible_connection: local
    blackarch:
      ansible_connection: local
      ansible_become: true
    blackarch_user:
      ansible_connection: local
      ansible_become: true
      ansible_become_user: '{{ user.name }}'
