---
all:
  hosts:
    laptop:
      ansible_connection: local
      ansible_become: true
    laptop_user:
      ansible_connection: local
    blackarch:
      ansible_connection: local
      ansible_become: true
    blackarch_user:
      ansible_connection: local
      ansible_become: true
      ansible_become_user: '{{ user.name }}'
laptop:
  hosts:
    laptop:
    laptop_user:
