- name: Install dotfile dependencies
  become: true
  become_user: root
  ansible.builtin.package:
    name:
      - ruby

- name: Check if dotfiles directory exists
  ansible.builtin.stat:
    path: "{{ dotfiles_dir }}"
  register: dotfiles_dir_stat

- name: Checkout dotfiles (via http)
  ansible.builtin.git:
    repo: 'https://github.com/narkatee/dotfiles'
    dest: "{{ dotfiles_dir }}"
  when:
    - not dotfiles_ssh
    - not dotfiles_dir_stat.stat.exists
  tags: dotfiles

- name: Checkout dotfiles (via ssh)
  ansible.builtin.git:
    repo: 'git@github.com:narkaTee/dotfiles.git'
    dest: "{{ dotfiles_dir }}"
  when:
    - dotfiles_ssh
    - not dotfiles_dir_stat.stat.exists
  tags: dotfiles

- name: Install dotfiles
  ansible.builtin.command:
    chdir: "{{ dotfiles_dir }}"
    cmd: "rake install"
  tags: dotfiles
