all:
  hosts:
    localhost:
      ansible_connection: local
      ansible_become: yes
    localhost_user:
      ansible_connection: local
      ansible_become: yes
      ansible_become_user: '{{ user.name }}'
