- name: Checkout dotfiles
  ansible.builtin.git:
    repo: 'https://github.com/narkatee/dotfiles'
    dest: "{{ ansible_facts['user_dir'] }}/dotfiles"
- name: Install dotfiles
  ansible.builtin.command:
    chdir: "{{ ansible_facts['user_dir'] }}/dotfiles"
    cmd: "rake install"
