---
driver:
  name: podman

platforms:
  - name: debian13
    image: docker.io/debian:13
  - name: debian12
    image: docker.io/debian:12

scenario:
  test_sequence:
    # - dependency
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
